# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ContractEndInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 10, 27, 16, 32, 45, 483649, tzinfo=utc))),
                ('numberofhoursworked', models.SmallIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPCApp.Contract')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('priceforanhour', models.SmallIntegerField()),
                ('numberofhours', models.SmallIntegerField()),
                ('numberofmounths', models.SmallIntegerField()),
                ('countinaweek', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CourseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timemask', models.BigIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPCApp.Course')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('grade', models.SmallIntegerField()),
                ('letter', models.CharField(max_length=2)),
                ('passportserialnumber', models.BigIntegerField()),
                ('passportissued', models.CharField(max_length=128)),
                ('homeaddress', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('parentname', models.CharField(max_length=64)),
                ('parentpassportserialnumber', models.BigIntegerField()),
                ('parentpassportissued', models.CharField(max_length=128)),
                ('parentinn', models.BigIntegerField()),
                ('parenthomeaddress', models.CharField(max_length=128)),
                ('parentphone', models.BigIntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 10, 27, 16, 32, 45, 478157, tzinfo=utc))),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('typeofuser', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='courseobject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPCApp.UserInfo'),
        ),
        migrations.AddField(
            model_name='contract',
            name='courseobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPCApp.CourseObject'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPCApp.Student'),
        ),
    ]
